X=MsgBox("Error while opening Google docs. do you want to fix it?",4+64,"Google docs")
X=MsgBox("Unable to fix it. scan your PC?",3+64,"Google docs")
X=MsgBox("we founf viruses, delete them?", 3+48,"G00g|e D0(s")
X=MsgBox("THE virus cant be deleted, would you like to end this process of google_docs.exe",3+16, "ALERT")
X=MsgBox("UNABLE TO END THIS PROCESS OF Google_docs.exe. PLEASE CONTRACT MICORSOFT THAT TO REMOVE VIRUS",2+16,"FATAL ERROR")
X=MsgBox("there is NO virus",1+32,"protecton")